# Generated by Django 5.0.2 on 2024-08-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_property_favourited'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='favourited',
            new_name='favorited',
        ),
    ]
