import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Modal from "./components/modal/Modal";

const inter = Inter({ subsets: ["latin"] });

// NOTE: Base layout file similar to django html page which uses {% block %}
export const metadata: Metadata = {
  title: "AirBnB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <div className="pt-32">
          {children}
        </div>
      </body>
    </html>
  );
}
