import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modal/LoginModal";
import SignUpModal from "./components/modal/SignUpModal";
import { AuthProvider } from "./contexts/AuthContext";
import { FiltersProvider } from "./contexts/FiltersContext";

const inter = Inter({ subsets: ["latin"] });

// NOTE: Base layout file similar to django html page which uses {% block %}
export const metadata: Metadata = {
  title: "AirBnB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <FiltersProvider>
            <Navbar />
            <div className="pt-32">
              {children}
            </div>
            <LoginModal />
            <SignUpModal />
          </FiltersProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
